//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstGrade
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int ID { get; set; }
        public string ssn { get; set; }
        public Nullable<System.DateTime> hire { get; set; }
        public Nullable<double> pay { get; set; }
        public int personID { get; set; }
    
        public virtual person person { get; set; }
    }
}
